config/routes.rb
Rails.application.routes.draw do

	resources :users
	resources :accounts
	resources :deposits
	resources :transfers
	resources :withdrawals
	resources :transaction
	resources :borrows

	root 'static_pages#home'
	get '/help', to: 'static_pages#help'
	get '/about', to: 'static_pages#about'
	get '/contact', to: 'static_pages#contact'
	get '/signup', to: 'users#new'
	get '/friends', to: 'users#friends'
	get 'friendships/create'
	get 'friendships/accept'
	get 'friendships/decline'
	get 'friendships/cancel'
	get 'borrows/cancel'
	get 'borrows/accept/:id', to: 'borrows#accept'
	get 'borrows/decline/:id', to: 'borrows#decline'
	post '/accounts/activate/:id', to: 'accounts#activate'
	post '/accounts/close/:id', to: 'accounts#close'
    get '/deposits/approve/:id', to: 'deposits#approve'
    get '/deposits/decline/:id', to: 'deposits#decline'
    get '/withdrawals/approve/:id', to: 'withdrawals#approve'
    get '/withdrawals/decline/:id', to: 'withdrawals#decline'
    get '/transfers/approve/:id', to: 'transfers#approve'
    get '/transfers/decline/:id', to: 'transfers#decline'
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

	









	
end

app/models/withdrawal.rb
class Withdrawal < ActiveRecord::Base
  belongs_to :user
  belongs_to :admin, class_name: "User", foreign_key: "admin_id"

  validates :user_id, presence: true

  def self.request(user, admin)
    unless user == admin
      transaction do
        create(user: user, admin: admin, status: 'requested')
        create(user: admin, admin: user, status: 'pending')
      end
    end
  end

  def self.accept(user, admin)
    transaction do
      accept_one_side(user, admin)
      accept_one_side(admin, user)
    end
  end

  def self.breakup(user, admin)
    transaction do
      destroy(find_by_user_id_and_admin_id(user, admin))
      destroy(find_by_user_id_and_admin_id(admin, user))
    end
  end

  private

  def self.accept_one_side(user, admin)
    request = find_by_user_id_and_admin_id(user, admin)
    request.status = 'accepted'
    request.save!
  end
end

app/controllers/withdrawals_controller.rb
class WithdrawalsController < ApplicationController
  before_action :set_withdrawal, only: [:show, :edit, :update, :destroy, :approve]

  # GET /withdrawals
  # GET /withdrawals.json
  def index
    @withdrawals = []
    if current_user.admin?
        @withdrawals = Withdrawal.all
    else
        @withdrawals = Withdrawal.where(user_id: current_accounts.collect{|x| x.acct_number})
		#Withdrawal.find_by_sql("SELECT * FROM withdrawals WHERE user_id IN (SELECT acct_number FROM accounts WHERE owner = current_user)".gsub("current_user", current_user.id.to_s))
    end
  end

  # GET /withdrawals/1
  # GET /withdrawals/1.json
  def show
  end

  # GET /withdrawals/new
  def new
    @withdrawal = Withdrawal.new
  end

  # GET /withdrawals/1/edit
  def edit
  end

  # POST /withdrawals
  # POST /withdrawals.json
  def create
    @withdrawal = Withdrawal.new(withdrawal_params)
	@account = Account.select{|x| x.acct_number == @withdrawal.user_id.to_s }[0]
	#Account.find_by_sql("SELECT * FROM accounts WHERE acct_number = id".gsub("id", @withdrawal.user_id.to_s))[0]
    if @withdrawal.nil? || @withdrawal.amount < 0
      flash[:danger] = "No withdrawal request passed to controller"
	  redirect_to :back
	  return
    elsif @withdrawal.amount >= @account.balance
		flash[:danger] = "Insufficient Balance"
		redirect_to :back
		return
	else
      Withdrawal.request(@user, @admin)
    end
    
    if @withdrawal.amount.nil?
      flash[:danger] = "Invalid Withdrawal: No Amount"
      redirect_to "/withdrawals/new"
      return
    end
	
	if @withdrawal.amount <= 0
		flash[:danger] = "Your requested withdrawal must be a positive number! Stop trying to rob us!"
		redirect_to :back
		return
	end
	
    
    respond_to do |format|
		  if @withdrawal.save
			if @withdrawal.amount <= 1000
				@withdrawal.update(status: 'APPROVED')
				@account = Account.select{|x| x.acct_number == @withdrawal.user_id.to_s }[0]
				#Account.find_by_sql("SELECT * FROM accounts WHERE acct_number = id".gsub("id", @withdrawal.user_id.to_s))[0]
				new_balance = @account.balance -= @withdrawal.amount
				Account.where(acct_number: @withdrawal.user_id).update_all(balance: new_balance)
				@account.save
				format.html { redirect_to @withdrawal, notice: 'Your request has been approved.' }
				format.json { render :show, status: :created, location: @withdrawal }
			else 
				format.html { redirect_to @withdrawal, notice: 'Your request  has been sent. Pending Approval from the admin.' }
				format.json { render :show, status: :created, location: @withdrawal }
			end
		  else
			format.html { render :new }
			format.json { render json: @withdrawal.errors, status: :unprocessable_entity }
		  end
	end
  end

  # PATCH/PUT /withdrawals/1
  # PATCH/PUT /withdrawals/1.json
  def update
    respond_to do |format|
      if @withdrawal.update(withdrawal_params)
        format.html { redirect_to @withdrawal, notice: 'Withdrawal was successfully updated.' }
        format.json { render :show, status: :ok, location: @withdrawal }
      else
        format.html { render :edit }
        format.json { render json: @withdrawal.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def approve
       @account = Account.select{|x| x.acct_number == @withdrawal.user_id.to_s }[0]
	   #Account.find_by_sql("SELECT * FROM accounts WHERE acct_number = id".gsub("id", @withdrawal.user_id.to_s))[0]
       new_balance = @account.balance -= @withdrawal.amount
       Account.where(acct_number: @withdrawal.user_id).update_all(balance: new_balance)
       @account.save
              
       Withdrawal.where(:id => params[:id]).update_all(status: 'APPROVED')
       @withdrawal = Withdrawal.find(params[:id])
       flash[:success] = "Approved Withdrawal"
       redirect_to @withdrawal
    end
    
 def decline
  Withdrawal.where(:id => params[:id]).update_all(status: 'DECLINED')
  @withdrawal = Withdrawal.find(params[:id])
  flash[:success] = "Declined Withdrawal"
  redirect_to @withdrawal
 end

  # DELETE /withdrawals/1
  # DELETE /withdrawals/1.json
  def destroy
    @withdrawal.destroy
    respond_to do |format|
      format.html { redirect_to withdrawals_url, notice: 'Withdrawal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_withdrawal
      @withdrawal = Withdrawal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def withdrawal_params
      params.require(:withdrawal).permit(:user_id, :date, :amount)
    end

    def setup_deposit
      @user = User.find(session[:user_id])
      @admin = User.find(1)
    end

end

app/views/withdrawals/_form.html.erb
<%= form_for(@withdrawal) do |f| %>
  <% if @withdrawal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@withdrawal.errors.count, "error") %> prohibited this withdrawal from being saved:</h2>

      <ul>
      <% @withdrawal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Account" %>
    <%= f.select :user_id, current_accounts.select{|x| x.status == "active" || x.status == "ACTIVE" }.collect{|x| x.acct_number} %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/withdrawals/edit.html.erb
<h1>Editing Withdrawal</h1>

<%= render 'form' %>

<%= link_to 'Show', @withdrawal %> |
<%= link_to 'Back', withdrawals_path %>

app/views/withdrawals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Withdrawal History</h1>

<table width="500">
  <thead>
    <tr>
      <th>Account</th>
      <th>Date</th>
      <th>Amount</th>
      <th>Status</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @withdrawals.each do |withdrawal| %>
      <tr height="20">
        <td><%= withdrawal.user_id %></td>
        <td><%= withdrawal.date %></td>
        <% if withdrawal.amount %>
			<td>$<%= sprintf("%.2f",withdrawal.amount) %></td>
		<% else %>
			<td>$<%= "0.00" %></td>
		<% end %>
		<td><%= withdrawal.status %></td>
        <% if current_user.admin? %>
			<td><u><%= link_to "Approve",:controller => :withdrawals, :action => :approve, :id => withdrawal.id %></td>
			<td><u><%= link_to "Decline",:controller => :withdrawals, :action => :decline, :id => withdrawal.id %></td>
		<% else %>
			<td><u><%= link_to 'Show', withdrawal %></u></td>
			<td><u><%= link_to 'Destroy', withdrawal, method: :delete, data: { confirm: 'Are you sure?' } %></u></td>
		<% end %>
	  </tr>
    <% end %>
  </tbody>
</table>

<br>

<% unless admin? %>
	<%= link_to 'New Withdrawal', new_withdrawal_path %>
<% end %>

app/views/withdrawals/new.html.erb
<h1>New Withdrawal</h1>

<%= render 'form' %>

<%= link_to 'Back', withdrawals_path %>

app/views/withdrawals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <b><%= link_to @withdrawal.user_id, :controller => :accounts, :action => :show, :id => current_accounts.select{|x| x.acct_number == @withdrawal.user_id.to_s}.collect{|x| x.id} %></b>
</p>

<p>
  <strong>Date:</strong>
  <%= @withdrawal.date %>
</p>

<p>
  <strong>Withdrawal Amount:</strong>
  <% if @withdrawal.amount %>
	$<%= sprintf("%.2f",@withdrawal.amount) %>
  <% else %>
	$<%= "0.00" %>
  <% end %>
</p>

<%= link_to 'Back', withdrawals_path %>