config/routes.rb
Rails.application.routes.draw do

	resources :users
	resources :accounts
	resources :deposits
	resources :transfers
	resources :withdrawals
	resources :transaction
	resources :borrows

	root 'static_pages#home'
	get '/help', to: 'static_pages#help'
	get '/about', to: 'static_pages#about'
	get '/contact', to: 'static_pages#contact'
	get '/signup', to: 'users#new'
	get '/friends', to: 'users#friends'
	get 'friendships/create'
	get 'friendships/accept'
	get 'friendships/decline'
	get 'friendships/cancel'
	get 'borrows/cancel'
	get 'borrows/accept/:id', to: 'borrows#accept'
	get 'borrows/decline/:id', to: 'borrows#decline'
	post '/accounts/activate/:id', to: 'accounts#activate'
	post '/accounts/close/:id', to: 'accounts#close'
    get '/deposits/approve/:id', to: 'deposits#approve'
    get '/deposits/decline/:id', to: 'deposits#decline'
    get '/withdrawals/approve/:id', to: 'withdrawals#approve'
    get '/withdrawals/decline/:id', to: 'withdrawals#decline'
    get '/transfers/approve/:id', to: 'transfers#approve'
    get '/transfers/decline/:id', to: 'transfers#decline'
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

	









	
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { email.downcase! }
	validates :name, presence: true, length: {maximum: 20 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 40 }, format: { with: VALID_EMAIL_REGEX },
					  uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
	
	has_many :friendships
	has_many :friends, through: :friendships, validate: "status = 'accepted'"
	has_many :requested_friends, through: :friendships, source: :friend, validate: "status = 'requested'"
	has_many :pending_friends, through: :friendships, source: :friend, validate: "status = 'pending'"
	
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end
	
	def self.search(search)
		if search
			where("name LIKE ? OR email LIKE ?", "%#{search}%", "%#{search}%")
		else
			[]
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	helper :friendship
	
	before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
	before_action :correct_user, only: [:edit, :update]
	before_action :is_admin?, only: [:destroy]

  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
		if @user.admin?
			flash[:success] = "New Administrator has been created!"
			redirect_to root_url
		else
		  log_in @user
		  flash[:success] = "Account creation successful! Welcome to the Bank of Bogus Transactions!"
		  redirect_to @user
		end
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Account update successful!"
      redirect_to @user
	  else
	    render 'edit'
	  end
  end
  
  def destroy
	@user = User.find(params[:id])
	if @user.master?
		flash[:danger] = "Failed: Cannot delete Master Admin!"
		redirect_to current_user
	else
		User.find(params[:id]).destroy
		flash[:success] = "User Deleted"
		redirect_to users_url
	end
  end
  
  def index
	@users = []
	
	if current_user.admin?
		if params[:search]
			@users = User.search(params[:search]).paginate(page: params[:page])
		else
			@users = User.paginate(page: params[:page])
		end
		if @users.empty?
			flash.now[:danger] = "No Results Found"
		end
	else
		if params[:search]
			if params[:search].blank?
				@users = []
			else
				@users = User.search(params[:search]).paginate(page: params[:page])
			end
			if @users.empty?
				flash.now[:danger] = "No Results Found"
			end
		else
			@users = []
		end
	end
  end
  
  def friends
	@users = []
	Friendship.all.each do |friendship|
		if friendship.user == current_user
			@users.push(friendship.friend)
		end
	end
  end
  
  private
  
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
	end
	
	def logged_in_user
		unless logged_in?
			
			flash[:danger] = "Please log in."
			redirect_to login_url
		end
	end
	
	def correct_user
		@user = User.find(params[:id])
		redirect_to(root_url) unless current_user?(@user)
	end
	
	def is_admin?
		redirect_to(root_url) unless current_user.admin?
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { size: 80 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
	
	def index
	@users = []
	
	if current_user.admin?
		if params[:search]
			@users = User.search(params[:search]).paginate(page: params[:page])
		else
			@users = User.paginate(page: params[:page])
		end
		if @users.empty?
			flash.now[:danger] = "No Results Found"
		end
	else
		if params[:search]
			if params[:search].blank?
				@users = []
			else
				@users = User.search(params[:search]).paginate(page: params[:page])
			end
			if @users.empty?
				flash.now[:danger] = "No Results Found"
			end
		else
			@users = []
		end
	end
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', object: @user %>

	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>

	<%= f.label :email %>
	<%= f.email_field :email, class: 'form-control' %>

	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control' %>

	<%= f.label :password_confirmation, "Confirmation" %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>

	<%= f.submit yield(:button_text), class: "btn btn-primary" %>
	
	<% if current_page?(signup_path) %>
		<p>Already have an account? <%= link_to "Log In", login_path %></p>
	<% end %>
<% end %>

app/views/users/_formAdmin.html.erb
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', object: @user %>

	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>

	<%= f.label :email %>
	<%= f.email_field :email, class: 'form-control' %>

	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control' %>

	<%= f.label :password_confirmation, "Confirmation" %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>
	
	<div class = "col-md-1 >
		<%= f.label :admin %>
		<%= f.check_box :admin %>
	</div>
	
	<%= f.submit yield(:button_text), class: "btn btn-primary" %>
	
	<% if current_page?(signup_path) %>
		<p>Already have an account? <%= link_to "Log In", login_path %></p>
	<% end %>
<% end %>

app/views/users/_user.html.erb
<li>
	<% if !current_user?(user) %>
		<%= gravatar_for user, size: 50 %>
		<%= link_to user.name, user %>
		<% if current_user.admin? %>
			| <%= link_to "Delete", user, method: :delete, data: {confirm: "You Sure?" } %>
		<% elsif !current_user.admin? %>
			<% friends = Friendship.find_by_user_id_and_friend_id(current_user, user) %>
			<% if friends %>
				<% if friends.status == 'accepted' %>
					| <%= link_to "Borrow Request", new_borrow_path(id: current_user.id, friend_id: user) %>
					| <%= link_to "Remove Friend", friendships_cancel_path(friend_param: user) %>
				<% elsif friends.status == 'pending' %>
					| <%= link_to "Accept", friendships_accept_path(friend_param: user) %> 
					| <%= link_to "Decline", friendships_decline_path(friend_param: user) %>
				<% else %>
					| <%= link_to "Cancel", friendships_cancel_path(friend_param: user) %>
				<% end %>
			<% else %>
				| <%= link_to "Add Friend", friendships_create_path(friend_param: user) %>
			<% end %>
		<% end %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit Profile") %>
<% provide(:button_text, "Save Changes") %>
<h1>Update your Information</h1>

<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= render 'form' %>
		
		<div class = "gravatar_edit">
			<%=gravatar_for @user %>
			<a href = "http://gravatar.com/emails" target="_blank">Change</a>
		</div>
	</div>
</div>

app/views/users/friends.html.erb
<% provide(:title, 'Friends') %>
<h1>Friends</h1>


<%= form_tag(users_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Name or Email" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<% if @users.empty? %>
	<!-- do nothing -->
<% else %>
	


	<ul class = "users">
		<%= render @users %>
	</ul>
	

	
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<% if admin? %>
	<h1>All Users</h1>
<% else %>
	<h1>User Search</h1>
<% end %>

<%= form_tag(users_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Name or Email" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<% if @users.empty? %>
	<!-- do nothing -->
<% else %>
	<%= will_paginate %>


	<ul class = "users">
		<%= render @users %>
	</ul>
	

	<%= will_paginate %>
<% end %>


app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<% provide(:button_text, "Create My Account") %>
<h1>Sign Up</h1>
<div class = "row">
	<% if current_user %>
		<% if current_user.admin? %>
			<div class = "col-md-6 col-md-offset-3">
				<%= render 'formAdmin' %>
			</div>
		<% else %>
			<div class = "col-md-6 col-md-offset-3">
				<%= render 'form' %>
			</div>
		<% end %>
	<% else %>
		<div class = "col-md-6 col-md-offset-3">
			<%= render 'form' %>
		</div>
	<% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class = "row">
	<aside class = "col-md-4">
		<section class = "user_info">
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %><br>
				<%= @user.email %>
      </h1>
    </section>
	</aside>
</div>