config/routes.rb
Rails.application.routes.draw do

	resources :users
	resources :accounts
	resources :deposits
	resources :transfers
	resources :withdrawals
	resources :transaction
	resources :borrows

	root 'static_pages#home'
	get '/help', to: 'static_pages#help'
	get '/about', to: 'static_pages#about'
	get '/contact', to: 'static_pages#contact'
	get '/signup', to: 'users#new'
	get '/friends', to: 'users#friends'
	get 'friendships/create'
	get 'friendships/accept'
	get 'friendships/decline'
	get 'friendships/cancel'
	get 'borrows/cancel'
	get 'borrows/accept/:id', to: 'borrows#accept'
	get 'borrows/decline/:id', to: 'borrows#decline'
	post '/accounts/activate/:id', to: 'accounts#activate'
	post '/accounts/close/:id', to: 'accounts#close'
    get '/deposits/approve/:id', to: 'deposits#approve'
    get '/deposits/decline/:id', to: 'deposits#decline'
    get '/withdrawals/approve/:id', to: 'withdrawals#approve'
    get '/withdrawals/decline/:id', to: 'withdrawals#decline'
    get '/transfers/approve/:id', to: 'transfers#approve'
    get '/transfers/decline/:id', to: 'transfers#decline'
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

	









	
end

app/models/deposit.rb
class Deposit < ActiveRecord::Base
  belongs_to :user
  belongs_to :admin, class_name: "User", foreign_key: "admin_id"

  validates :user_id, presence: true

  def self.request(user, admin)
    unless user == admin
      transaction do
        create(user: user, admin: admin, status: 'requested')
        create(user: admin, admin: user, status: 'pending')
      end
    end
  end

  def self.accept(user, admin)
    transaction do
      accept_one_side(user, admin)
      accept_one_side(admin, user)
    end
  end

  def self.breakup(user, admin)
    transaction do
      destroy(find_by_user_id_and_admin_id(user, admin))
      destroy(find_by_user_id_and_admin_id(admin, user))
    end
  end

private

def self.accept_one_side(user, admin)
  request = find_by_user_id_and_admin_id(user, admin)
  request.status = 'accepted'
    request.save!
  end
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  before_action :set_deposit, only: [:show, :edit, :update, :destroy, :approve]
  before_filter :setup_deposit

                  # GET /deposits
  # GET /deposits.json
  def index
    @deposits = []
    if current_user.admin?
        @deposits = Deposit.all
    else
        @deposits = Deposit.where(user_id: current_accounts.collect{|x| x.acct_number})
    end
  end

  # GET /deposits/1
  # GET /deposits/1.json
  def show
  end

  # GET /deposits/new
  def new
    @deposit = Deposit.new
  end

  # GET /deposits/1/edit
  def edit
  end

  # POST /deposits
  # POST /deposits.json
  def create
    @deposit = Deposit.new(deposit_params) 
    if @deposit.nil? || @deposit.amount < 0
      flash[:danger] = "No Deposit request passed to controller"
	  redirect_to :back
	  return
    else
      Deposit.request(@user, User.find(1))
    end
    
    if @deposit.amount.nil?
      flash[:danger] = "Invalid Deposit: No Amount"
      redirect_to "/deposits/new"
      return
    end
    
    respond_to do |format|
      if @deposit.save
        format.html { redirect_to @deposit, notice: 'Your request  has been sent. Pending Approval from the admin.' }
        format.json { render :show, status: :created, location: @deposit }
      else
        format.html { render :new }
        format.json { render json: @deposit.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def approve
     @account = Account.select{|x| x.acct_number == @deposit.user_id.to_s }[0]
	 #Account.find_by_sql("SELECT * FROM accounts WHERE acct_number = id".gsub("id", @deposit.user_id.to_s))[0]
     new_balance = @account.balance += @deposit.amount
     Account.where(acct_number: @deposit.user_id).update_all(balance: new_balance)
     @account.save
            
     Deposit.where(:id => params[:id]).update_all(status: 'APPROVED')
     @deposit = Deposit.find(params[:id])
     flash[:success] = "Approved Deposit"
     redirect_to @deposit
  end
  
  def decline
   Deposit.where(:id => params[:id]).update_all(status: 'DECLINED')
   @deposit = Deposit.find(params[:id])
   flash[:success] = "Declined Deposit"
   redirect_to @deposit
 end

  # PATCH/PUT /deposits/1
  # PATCH/PUT /deposits/1.json
  def update
    respond_to do |format|
      if @deposit.update(deposit_params)
        format.html { redirect_to @deposit, notice: 'Deposit was successfully updated.' }
        format.json { render :show, status: :ok, location: @deposit }
      else
        format.html { render :edit }
        format.json { render json: @deposit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deposits/1
  # DELETE /deposits/1.json
  def destroy
    @deposit.destroy
    respond_to do |format|
      format.html { redirect_to deposits_url, notice: 'Deposit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deposit
      @deposit = Deposit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deposit_params
      params.require(:deposit).permit(:user_id, :date, :amount)
    end

    def setup_deposit
      @user = User.find(session[:user_id])
      @admin = User.find(1)
    end
end

app/views/deposits/_form.html.erb
<%= form_for(@deposit) do |f| %>
  <% if @deposit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deposit.errors.count, "error") %> prohibited this deposit from being saved:</h2>

      <ul>
      <% @deposit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Account" %>
    <%= f.select :user_id, current_accounts.select{|x| x.status == "active" || x.status == "ACTIVE" }.collect{|x| x.acct_number} %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deposits/edit.html.erb
<h1>Editing Deposit</h1>

<%= render 'form' %>

<%= link_to 'Show', @deposit %> |
<%= link_to 'Back', deposits_path %>

app/views/deposits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Deposit History</h1>

<table width="500">
  <thead>
    <tr>
      <th>Account</th>
      <th>Date</th>
      <th>Amount</th>
      <th>Status</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
	<% @deposits.each do |deposit| %>
		<% if deposit.user_id.to_s.length == 9 %>
		  <tr height="20">
			<td><%= deposit.user_id %></td>
			<td><%= deposit.date %></td>
			<% if deposit.amount %>
				<td>$<%= sprintf("%.2f",deposit.amount) %></td>
			<% else %>
				<td>$<%= "0.00" %></td>
			<% end %>
			<td><%= deposit.status %></td>
			<% if current_user.admin? %>
				<% if deposit.status == "APPROVED" || deposit.status == "DECLINED" %>
					<td><u><%= link_to 'Show', deposit %></u></td>
				<% else %>
					<td><u><%= link_to "Approve",:controller => :deposits, :action => :approve, :id => deposit.id %></u></td>
					<td><u><%= link_to "Decline",:controller => :deposits, :action => :decline, :id => deposit.id %></u></td>
				<% end %>
			<% else %>
				<td><u><%= link_to 'Show', deposit %></u></td>
				<td><u><%= link_to 'Destroy', deposit, method: :delete, data: { confirm: 'Are you sure?' } %></u></td>
			<% end %>
		<% end %>
	  </tr>
    <% end %>
  </tbody>
</table>

<br>
<% unless admin? %>
	<%= link_to 'New Deposit', new_deposit_path %>
<% end %>

app/views/deposits/new.html.erb
<h1>New Deposit</h1>

<%= render 'form' %>

<%= link_to 'Back', deposits_path %>

app/views/deposits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <b><%= link_to @deposit.user_id, :controller => :accounts, :action => :show, :id => current_accounts.select{|x| x.acct_number == @deposit.user_id.to_s}.collect{|x| x.id} %></b>
</p>

<p>
  <strong>Date:</strong>
  <%= @deposit.date %>
</p>

<p>
  <strong>Deposit Amount:</strong>
  <% if @deposit.amount %>
  	$<%= sprintf("%.2f",@deposit.amount) %>
  <% else %>
  	$<%= "0.00" %>
  <% end %>
</p>

<%= link_to 'Back', deposits_path %>