config/routes.rb
Rails.application.routes.draw do

	resources :users
	resources :accounts
	resources :deposits
	resources :transfers
	resources :withdrawals
	resources :transaction
	resources :borrows

	root 'static_pages#home'
	get '/help', to: 'static_pages#help'
	get '/about', to: 'static_pages#about'
	get '/contact', to: 'static_pages#contact'
	get '/signup', to: 'users#new'
	get '/friends', to: 'users#friends'
	get 'friendships/create'
	get 'friendships/accept'
	get 'friendships/decline'
	get 'friendships/cancel'
	get 'borrows/cancel'
	get 'borrows/accept/:id', to: 'borrows#accept'
	get 'borrows/decline/:id', to: 'borrows#decline'
	post '/accounts/activate/:id', to: 'accounts#activate'
	post '/accounts/close/:id', to: 'accounts#close'
    get '/deposits/approve/:id', to: 'deposits#approve'
    get '/deposits/decline/:id', to: 'deposits#decline'
    get '/withdrawals/approve/:id', to: 'withdrawals#approve'
    get '/withdrawals/decline/:id', to: 'withdrawals#decline'
    get '/transfers/approve/:id', to: 'transfers#approve'
    get '/transfers/decline/:id', to: 'transfers#decline'
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

	









	
end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User", foreign_key: "friend_id"

  validates :from, presence: true
  validates :to, presence: true

  def self.request(p, sender, friend)
    startdate = Date.new(p["start(1i)"].to_i, p["start(2i)"].to_i, p["start(3i)"].to_i)
	effectivedate = Date.new(p["effective(1i)"].to_i, p["effective(2i)"].to_i, p["effective(3i)"].to_i)
    unless p[:to] == p[:from]
      transaction do
        create(from: p[:from], to: p[:to], amount: p[:amount], status: 'complete', sender: sender, recipient: friend, start: startdate, effective: effectivedate)
      end
    end
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]
  before_filter :setup_transfer, only: [:create, :update, :destroy, :approve]

  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = []
    if current_user.admin?
        @transfers = Transfer.all
    else
        @transfers = Transfer.where(from: current_accounts.collect{|x| x.acct_number}) + Transfer.where(to: current_accounts.collect{|x| x.acct_number})      
    end
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
  end

  # GET /transfers/new
  def new
    @transfer = Transfer.new
  end

  # GET /transfers/1/edit
  def edit
  end

  # POST /transfers
  # POST /transfers.json
  def create
    @transfer = Transfer.request(transfer_params, @user.name, @friend.name)
    @from_account = Account.find_by_acct_number(params[:transfer][:from])
    if @transfer.nil? || @transfer.amount < 0
      flash[:danger] = "Invalid Transfer Amount"
	  redirect_to :back
	  return
    elsif @transfer.amount >= @from_account.balance
		flash[:danger] = "Insufficient Balance"
		redirect_to :back
		return
	end
    
    if @transfer.to.nil? || @transfer.to == ""
      flash[:danger] = "Invalid Transfer: No Participant"
      redirect_to "/transfers/new"
      return
    end
    
    respond_to do |format|
      if @transfer.save
		@to_account = Account.find_by_acct_number(params[:transfer][:to])
		new_balance = @to_account.balance += @transfer.amount
		Account.where(acct_number: @transfer.to).update_all(balance: new_balance)
		@to_account.save
		
		@from_account = Account.find_by_acct_number(params[:transfer][:from])
		new_balance2 = @from_account.balance -= @transfer.amount
		Account.where(acct_number: @transfer.from).update_all(balance: new_balance2)
		@from_account.save
			  
		flash[:success] = "Approved Transfer"
        format.html { redirect_to @transfer, notice: 'Your transfer has been successfully processed.' }
        format.json { render :show, status: :created, location: @transfer }
      else
        format.html { render :new }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def approve
    @to_account = Account.find_by_sql("SELECT * FROM accounts WHERE acct_number = id".gsub("id", @transfer.to))[0]
    new_balance = @to_account.balance += @transfer.amount
    Account.where(acct_number: @transfer.to).update_all(balance: new_balance)
    @to_account.save
    
    @from_account = Account.find_by_sql("SELECT * FROM accounts WHERE acct_number = id".gsub("id", @transfer.from))[0]
    new_balance2 = @from_account.balance -= @transfer.amount
    Account.where(acct_number: @transfer.from).update_all(balance: new_balance2)
    @from_account.save
          
    Transfer.where(:id => params[:id]).update_all(status: 'APPROVED')
    @transfer = Transfer.find(params[:id])
    flash[:success] = "Approved Transfer"
    redirect_to @transfer
 end
 
 def decline
   Transfer.where(:id => params[:id]).update_all(status: 'DECLINED')
   @transfer = Transfer.find(params[:id])
   flash[:success] = "Declined Transfer"
   redirect_to @transfer
 end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to @transfer, notice: 'Transfer was successfully updated.' }
        format.json { render :show, status: :ok, location: @transfer }
      else
        format.html { render :edit }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to transfers_url, notice: 'Transfer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.require(:transfer).permit(:from, :to, :amount, :start, :effective)
    end

    def setup_transfer
      @user = User.find(session[:user_id])
      @friend = User.find(Account.find_by_acct_number(params[:transfer][:to]).owner.to_i)
    end
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/transfers/_form.html.erb
<%= form_for(@transfer) do |f| %>
  <% if @transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
      <% @transfer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= f.label :from %>
    <%= f.select :from, current_accounts.select{|x| x.status == "active" || x.status == "ACTIVE" }.collect{|x| x.acct_number} %>
  </div>
  <div class="field">
    <%= f.label :to %><br>
	<%= f.select :to, Account.all.select{|x| Friendship.exists?(current_user, User.find(x.owner.to_i)) }.collect{|x| x.acct_number } %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.date_select :start %>
  </div>
  <div class="field">
    <%= f.label :effective %><br>
    <%= f.date_select :effective %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transfers/edit.html.erb
<h1>Editing Transfer</h1>

<%= render 'form' %>

<%= link_to 'Show', @transfer %> |
<%= link_to 'Back', transfers_path %>

app/views/transfers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transfer History</h1>

<table width="650">
  <thead>
    <tr>
      <th>From Account</th>
      <th>To Account</th>
      <th>Amount</th>
      <th>Status</th>
      <th>Start</th>
      <th>Effective</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @transfers.each do |transfer| %>
		<% if current_user.name == transfer.sender || current_user.name == transfer.recipient %>
			<tr height="50">
				<td width = "175" ><%= transfer.sender + " - " + transfer.from %></td>
				<td width = "175" ><%= transfer.recipient + " - " + transfer.to %></td>
				<% if transfer.amount %>
					<td width = "75">$<%= sprintf("%.2f",transfer.amount) %></td>
				<% else %>
					<td width = "75">$<%= "0.00" %></td>
				<% end %>
				<td width = "175" ><%= transfer.status %></td>
				<td width = "175" ><%= transfer.start %></td>
				<td width = "175" ><%= transfer.effective %></td>
				<td><u><%= link_to 'Show', transfer %></u></td>
				<td><u><%= link_to 'Destroy', transfer, method: :delete, data: { confirm: 'Are you sure?' } %></u></td>
			</tr>
		<% elsif current_user.admin? %>
			<tr height="50">
				<td width = "175" ><%= transfer.sender + " - " + transfer.from %></td>
				<td width = "175" ><%= transfer.recipient + " - " + transfer.to %></td>
				<% if transfer.amount %>
					<td width = "75">$<%= sprintf("%.2f",transfer.amount) %></td>
				<% else %>
					<td width = "75">$<%= "0.00" %></td>
				<% end %>
				<td width = "175" ><%= transfer.status %></td>
				<td width = "175" ><%= transfer.start %></td>
				<td width = "175" ><%= transfer.effective %></td>
				<td><u><%= link_to 'Show', transfer %></td>

			</tr>
		<% end %>
    <% end %>
  </tbody>
</table>

<br>
<% unless admin? %>
	<%= link_to 'New Transfer', new_transfer_path %>
<% end %>

app/views/transfers/new.html.erb
<h1>New Transfer</h1>

<%= render 'form' %>

<%= link_to 'Back', transfers_path %>

app/views/transfers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From:</strong>
  <%= @transfer.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @transfer.to %>
</p>

<p>
  <strong>Transfer Amount:</strong>
  <% if @transfer.amount %>
	$<%= sprintf("%.2f",@transfer.amount) %>
  <% else %>
	$<%= "0.00" %>
  <% end %>
</p>

<p>
  <strong>Start:</strong>
  <%= @transfer.start %>
</p>

<p>
  <strong>Effective:</strong>
  <%= @transfer.effective %>
</p>

<%= link_to 'Back', transfers_path %>